version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalog
      MYSQL_USER: catalog
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: catalog
      DB_USER: catalog
      DB_PASSWORD: password
    ports:
      - "8080:8080"
