apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-login-app
  template:
    metadata:
      labels:
        app: java-login-app
    spec:
      containers:
        - name: app
          image: java-login-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/logindb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
