apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: catalog
spec:
  type: NodePort
  selector:
    app: product-catalog
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
